---
- name: playbook
  hosts: servers
  remote_user: bentley
  become: true
  tasks:
    - name: copy to target
      become: true
      copy:
        src: ~/Documents/nginx.tar
        dest: /home/zeeshan/Documents/destination
        mode: 0777
    - name: loading docker image
      become: true
      command: docker load -i /home/zeeshan/Documents/destination/nginx.tar 
    - name: running docker image
      become: true
      command: docker run -d nginx 
